services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wallpaper-manager-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules